-- phpMyAdmin SQL Dump
-- version 5.2.1
-- https://www.phpmyadmin.net/
--
-- Host: 127.0.0.1
-- Generation Time: Mar 09, 2024 at 10:19 AM
-- Server version: 10.4.28-MariaDB
-- PHP Version: 8.2.4

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `porai`
--

-- --------------------------------------------------------

--
-- Table structure for table `courses`
--

CREATE TABLE `courses` (
  `id` bigint(20) UNSIGNED NOT NULL,
  `category_id` bigint(11) UNSIGNED DEFAULT NULL,
  `sub_category_id` bigint(11) UNSIGNED DEFAULT NULL,
  `teacher_id` bigint(11) UNSIGNED DEFAULT NULL,
  `language_id` bigint(20) UNSIGNED DEFAULT NULL,
  `type_id` int(11) DEFAULT NULL,
  `coursetype` int(255) DEFAULT NULL,
  `name` varchar(255) DEFAULT NULL,
  `subject` varchar(255) DEFAULT NULL,
  `image` varchar(255) DEFAULT NULL,
  `fee` double(8,2) DEFAULT NULL,
  `discount` double(8,2) DEFAULT NULL,
  `discounttype` int(255) DEFAULT NULL,
  `organization_name` varchar(255) DEFAULT NULL,
  `course_hours` varchar(255) DEFAULT NULL,
  `course_level` varchar(255) DEFAULT NULL,
  `about` longtext DEFAULT NULL,
  `status` tinyint(1) NOT NULL DEFAULT 1,
  `startdate` varchar(11) DEFAULT NULL,
  `enddate` varchar(255) DEFAULT NULL,
  `speaker` int(11) DEFAULT NULL,
  `session` int(11) DEFAULT NULL,
  `day` int(11) DEFAULT NULL,
  `is_master` int(11) NOT NULL DEFAULT 0,
  `trailer_video_url` varchar(255) DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  `type` varchar(100) DEFAULT NULL,
  `child_category_id` bigint(20) UNSIGNED DEFAULT NULL,
  `pro_child_category_id` bigint(20) UNSIGNED DEFAULT NULL,
  `department_id` bigint(20) UNSIGNED DEFAULT NULL,
  `degree_id` bigint(20) UNSIGNED DEFAULT NULL,
  `university_id` bigint(20) UNSIGNED DEFAULT NULL,
  `section_id` bigint(20) UNSIGNED DEFAULT NULL,
  `tuition_fee` bigint(20) UNSIGNED DEFAULT NULL,
  `semester_fee` bigint(20) UNSIGNED DEFAULT NULL,
  `year_fee` bigint(20) UNSIGNED DEFAULT NULL,
  `course_duration` bigint(20) UNSIGNED DEFAULT NULL,
  `next_start_date` varchar(100) DEFAULT NULL,
  `application_deadline` varchar(100) DEFAULT NULL,
  `admission_process` longtext DEFAULT NULL,
  `accommodation` longtext DEFAULT NULL,
  `introduction` longtext DEFAULT NULL,
  `consultancy_fee` varchar(100) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

--
-- Dumping data for table `courses`
--

INSERT INTO `courses` (`id`, `category_id`, `sub_category_id`, `teacher_id`, `language_id`, `type_id`, `coursetype`, `name`, `subject`, `image`, `fee`, `discount`, `discounttype`, `organization_name`, `course_hours`, `course_level`, `about`, `status`, `startdate`, `enddate`, `speaker`, `session`, `day`, `is_master`, `trailer_video_url`, `created_at`, `updated_at`, `type`, `child_category_id`, `pro_child_category_id`, `department_id`, `degree_id`, `university_id`, `section_id`, `tuition_fee`, `semester_fee`, `year_fee`, `course_duration`, `next_start_date`, `application_deadline`, `admission_process`, `accommodation`, `introduction`, `consultancy_fee`) VALUES
(1, 48, 51, 176, NULL, NULL, 1, 'Fast Track Spoken English & Fluency', '', NULL, 2000.00, 10.00, 0, 'navieasoft limited', '04:12:32', 'beginner', '<p style=\"color: rgb(33, 37, 41); font-family: &quot;Open Sans&quot;, sans-serif; text-align: justify;\">This course is perfect for you if you are someone who&nbsp;<span style=\"font-weight: bolder;\">wants to start investing in the stock market.&nbsp;</span>There are many misconceptions or myths surrounding stock market investment. In this course, such myths are debunked so that you can start your investment journey with the right information and correct mind setup.&nbsp;</p><p dir=\"ltr\" style=\"color: rgb(33, 37, 41); font-family: &quot;Open Sans&quot;, sans-serif; text-align: justify;\">The course includes&nbsp;<span style=\"font-weight: bolder;\">understanding the stock market&nbsp;</span>and how it works, different types of stocks and stock market terminology, fundamental analysis techniques to evaluate stocks, risk management, the process of opening a brokerage account and making your first trade, and how to create your stock portfolio.&nbsp;</p><p dir=\"ltr\" style=\"color: rgb(33, 37, 41); font-family: &quot;Open Sans&quot;, sans-serif; text-align: justify;\">By the end of the course, participants will have a solid understanding of the stock market and be able to make informed investment decisions&nbsp;about<span style=\"font-weight: bolder;\">&nbsp;buying, holding, or selling a stock.</span></p><p dir=\"ltr\" style=\"color: rgb(33, 37, 41); font-family: &quot;Open Sans&quot;, sans-serif; text-align: justify;\">So without any further ado, enroll in the course right now!</p>', 1, NULL, NULL, NULL, NULL, NULL, 0, '', '2024-01-04 21:42:51', '2024-01-04 21:42:51', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(2, 48, 51, 177, NULL, NULL, 1, 'English for IBA-MBA Admission Preparation', '', NULL, 2000.00, 10.00, 0, 'navieasoft limited', '04:12:32', 'beginner', '<p style=\"color: rgb(33, 37, 41); font-family: \"Open Sans\", sans-serif; text-align: justify;\">This course is perfect for you if you are someone who <span style=\"font-weight: bolder;\">wants to start investing in the stock market. </span>There are many misconceptions or myths surrounding stock market investment. In this course, such myths are debunked so that you can start your investment journey with the right information and correct mind setup. </p><p dir=\"ltr\" style=\"color: rgb(33, 37, 41); font-family: \"Open Sans\", sans-serif; text-align: justify;\">The course includes <span style=\"font-weight: bolder;\">understanding the stock market </span>and how it works, different types of stocks and stock market terminology, fundamental analysis techniques to evaluate stocks, risk management, the process of opening a brokerage account and making your first trade, and how to create your stock portfolio. </p><p dir=\"ltr\" style=\"color: rgb(33, 37, 41); font-family: \"Open Sans\", sans-serif; text-align: justify;\">By the end of the course, participants will have a solid understanding of the stock market and be able to make informed investment decisions about<span style=\"font-weight: bolder;\"> buying, holding, or selling a stock.</span></p><p dir=\"ltr\" style=\"color: rgb(33, 37, 41); font-family: \"Open Sans\", sans-serif; text-align: justify;\">So without any further ado, enroll in the course right now!</p>', 1, NULL, NULL, NULL, NULL, NULL, 0, '', '2024-01-04 21:42:51', '2024-01-07 23:10:19', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(3, 49, 54, 178, NULL, NULL, 1, 'Technology in Leadership', '', NULL, 2000.00, 10.00, 0, 'navieasoft limited', '04:12:32', 'beginner', '<p style=\"color: rgb(33, 37, 41); font-family: \"Open Sans\", sans-serif; text-align: justify;\">This course is perfect for you if you are someone who <span style=\"font-weight: bolder;\">wants to start investing in the stock market. </span>There are many misconceptions or myths surrounding stock market investment. In this course, such myths are debunked so that you can start your investment journey with the right information and correct mind setup. </p><p dir=\"ltr\" style=\"color: rgb(33, 37, 41); font-family: \"Open Sans\", sans-serif; text-align: justify;\">The course includes <span style=\"font-weight: bolder;\">understanding the stock market </span>and how it works, different types of stocks and stock market terminology, fundamental analysis techniques to evaluate stocks, risk management, the process of opening a brokerage account and making your first trade, and how to create your stock portfolio. </p><p dir=\"ltr\" style=\"color: rgb(33, 37, 41); font-family: \"Open Sans\", sans-serif; text-align: justify;\">By the end of the course, participants will have a solid understanding of the stock market and be able to make informed investment decisions about<span style=\"font-weight: bolder;\"> buying, holding, or selling a stock.</span></p><p dir=\"ltr\" style=\"color: rgb(33, 37, 41); font-family: \"Open Sans\", sans-serif; text-align: justify;\">So without any further ado, enroll in the course right now!</p>', 1, NULL, NULL, NULL, NULL, NULL, 0, '', '2024-01-04 21:42:51', '2024-01-07 23:10:07', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(4, 48, 52, 186, NULL, NULL, 2, 'Digital Marketing Masterclass', '', NULL, 2000.00, 10.00, 0, 'navieasoft limited', '04:12:32', 'beginner', '<p style=\"color: rgb(33, 37, 41); font-family: \"Open Sans\", sans-serif; text-align: justify;\">This course is perfect for you if you are someone who <span style=\"font-weight: bolder;\">wants to start investing in the stock market. </span>There are many misconceptions or myths surrounding stock market investment. In this course, such myths are debunked so that you can start your investment journey with the right information and correct mind setup. </p><p dir=\"ltr\" style=\"color: rgb(33, 37, 41); font-family: \"Open Sans\", sans-serif; text-align: justify;\">The course includes <span style=\"font-weight: bolder;\">understanding the stock market </span>and how it works, different types of stocks and stock market terminology, fundamental analysis techniques to evaluate stocks, risk management, the process of opening a brokerage account and making your first trade, and how to create your stock portfolio. </p><p dir=\"ltr\" style=\"color: rgb(33, 37, 41); font-family: \"Open Sans\", sans-serif; text-align: justify;\">By the end of the course, participants will have a solid understanding of the stock market and be able to make informed investment decisions about<span style=\"font-weight: bolder;\"> buying, holding, or selling a stock.</span></p><p dir=\"ltr\" style=\"color: rgb(33, 37, 41); font-family: \"Open Sans\", sans-serif; text-align: justify;\">So without any further ado, enroll in the course right now!</p>', 1, NULL, NULL, NULL, NULL, NULL, 0, '', '2024-01-04 21:42:51', '2024-01-07 23:09:56', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(5, 50, 57, 184, NULL, NULL, 1, 'ToT for Innovative Teaching', '', NULL, 2000.00, 10.00, 0, 'navieasoft limited', '04:12:32', 'beginner', '<p style=\"color: rgb(33, 37, 41); font-family: \"Open Sans\", sans-serif; text-align: justify;\">This course is perfect for you if you are someone who <span style=\"font-weight: bolder;\">wants to start investing in the stock market. </span>There are many misconceptions or myths surrounding stock market investment. In this course, such myths are debunked so that you can start your investment journey with the right information and correct mind setup. </p><p dir=\"ltr\" style=\"color: rgb(33, 37, 41); font-family: \"Open Sans\", sans-serif; text-align: justify;\">The course includes <span style=\"font-weight: bolder;\">understanding the stock market </span>and how it works, different types of stocks and stock market terminology, fundamental analysis techniques to evaluate stocks, risk management, the process of opening a brokerage account and making your first trade, and how to create your stock portfolio. </p><p dir=\"ltr\" style=\"color: rgb(33, 37, 41); font-family: \"Open Sans\", sans-serif; text-align: justify;\">By the end of the course, participants will have a solid understanding of the stock market and be able to make informed investment decisions about<span style=\"font-weight: bolder;\"> buying, holding, or selling a stock.</span></p><p dir=\"ltr\" style=\"color: rgb(33, 37, 41); font-family: \"Open Sans\", sans-serif; text-align: justify;\">So without any further ado, enroll in the course right now!</p>', 1, NULL, NULL, NULL, NULL, NULL, 0, '', '2024-01-04 21:42:51', '2024-01-04 22:19:44', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(6, 50, 57, 184, NULL, NULL, 0, 'Proficiency in Effective Business Meetings', '', NULL, 2000.00, 10.00, 0, 'navieasoft limited', '04:12:32', 'beginner', '<p style=\"color: rgb(33, 37, 41); font-family: \"Open Sans\", sans-serif; text-align: justify;\">This course is perfect for you if you are someone who <span style=\"font-weight: bolder;\">wants to start investing in the stock market. </span>There are many misconceptions or myths surrounding stock market investment. In this course, such myths are debunked so that you can start your investment journey with the right information and correct mind setup. </p><p dir=\"ltr\" style=\"color: rgb(33, 37, 41); font-family: \"Open Sans\", sans-serif; text-align: justify;\">The course includes <span style=\"font-weight: bolder;\">understanding the stock market </span>and how it works, different types of stocks and stock market terminology, fundamental analysis techniques to evaluate stocks, risk management, the process of opening a brokerage account and making your first trade, and how to create your stock portfolio. </p><p dir=\"ltr\" style=\"color: rgb(33, 37, 41); font-family: \"Open Sans\", sans-serif; text-align: justify;\">By the end of the course, participants will have a solid understanding of the stock market and be able to make informed investment decisions about<span style=\"font-weight: bolder;\"> buying, holding, or selling a stock.</span></p><p dir=\"ltr\" style=\"color: rgb(33, 37, 41); font-family: \"Open Sans\", sans-serif; text-align: justify;\">So without any further ado, enroll in the course right now!</p>', 1, NULL, NULL, NULL, NULL, NULL, 0, '', '2024-01-04 21:42:51', '2024-01-07 23:09:38', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(7, 49, 55, 175, NULL, NULL, 2, 'Time Management for Best Productivity', '', NULL, 3000.00, 10.00, 0, 'navieasoft limited', '04:12:32', 'beginner', '<p style=\"color: rgb(33, 37, 41); font-family: \"Open Sans\", sans-serif; text-align: justify;\">This course is perfect for you if you are someone who <span style=\"font-weight: bolder;\">wants to start investing in the stock market. </span>There are many misconceptions or myths surrounding stock market investment. In this course, such myths are debunked so that you can start your investment journey with the right information and correct mind setup. </p><p dir=\"ltr\" style=\"color: rgb(33, 37, 41); font-family: \"Open Sans\", sans-serif; text-align: justify;\">The course includes <span style=\"font-weight: bolder;\">understanding the stock market </span>and how it works, different types of stocks and stock market terminology, fundamental analysis techniques to evaluate stocks, risk management, the process of opening a brokerage account and making your first trade, and how to create your stock portfolio. </p><p dir=\"ltr\" style=\"color: rgb(33, 37, 41); font-family: \"Open Sans\", sans-serif; text-align: justify;\">By the end of the course, participants will have a solid understanding of the stock market and be able to make informed investment decisions about<span style=\"font-weight: bolder;\"> buying, holding, or selling a stock.</span></p><p dir=\"ltr\" style=\"color: rgb(33, 37, 41); font-family: \"Open Sans\", sans-serif; text-align: justify;\">So without any further ado, enroll in the course right now!</p>', 1, NULL, NULL, NULL, NULL, NULL, 0, '', '2024-01-04 21:42:51', '2024-01-05 08:05:54', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(8, 49, 54, 182, NULL, NULL, 2, 'Leadership for First Line Managers', '', NULL, 7000.00, 1000.00, 1, 'navieasoft limited', '04:12:32', 'beginner', '<p style=\"color: rgb(33, 37, 41); font-family: \"Open Sans\", sans-serif; text-align: justify;\">This course is perfect for you if you are someone who <span style=\"font-weight: bolder;\">wants to start investing in the stock market. </span>There are many misconceptions or myths surrounding stock market investment. In this course, such myths are debunked so that you can start your investment journey with the right information and correct mind setup. </p><p dir=\"ltr\" style=\"color: rgb(33, 37, 41); font-family: \"Open Sans\", sans-serif; text-align: justify;\">The course includes <span style=\"font-weight: bolder;\">understanding the stock market </span>and how it works, different types of stocks and stock market terminology, fundamental analysis techniques to evaluate stocks, risk management, the process of opening a brokerage account and making your first trade, and how to create your stock portfolio. </p><p dir=\"ltr\" style=\"color: rgb(33, 37, 41); font-family: \"Open Sans\", sans-serif; text-align: justify;\">By the end of the course, participants will have a solid understanding of the stock market and be able to make informed investment decisions about<span style=\"font-weight: bolder;\"> buying, holding, or selling a stock.</span></p><p dir=\"ltr\" style=\"color: rgb(33, 37, 41); font-family: \"Open Sans\", sans-serif; text-align: justify;\">So without any further ado, enroll in the course right now!</p>', 1, NULL, NULL, NULL, NULL, NULL, 0, '', '2024-01-04 21:42:51', '2024-01-07 23:09:20', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(9, 48, 53, 265, NULL, NULL, 1, 'Fast Track Spoken English & Fluency', 'Practical Accounting Learning for Finance & Non-Finance Professionals', NULL, 4000.00, 500.00, 1, 'navieasoft limited', '04:12:32', 'beginner', '<p style=\"color: rgb(33, 37, 41); font-family: \"Open Sans\", sans-serif; text-align: justify;\">This course is perfect for you if you are someone who <span style=\"font-weight: bolder;\">wants to start investing in the stock market. </span>There are many misconceptions or myths surrounding stock market investment. In this course, such myths are debunked so that you can start your investment journey with the right information and correct mind setup. </p><p dir=\"ltr\" style=\"color: rgb(33, 37, 41); font-family: \"Open Sans\", sans-serif; text-align: justify;\">The course includes <span style=\"font-weight: bolder;\">understanding the stock market </span>and how it works, different types of stocks and stock market terminology, fundamental analysis techniques to evaluate stocks, risk management, the process of opening a brokerage account and making your first trade, and how to create your stock portfolio. </p><p dir=\"ltr\" style=\"color: rgb(33, 37, 41); font-family: \"Open Sans\", sans-serif; text-align: justify;\">By the end of the course, participants will have a solid understanding of the stock market and be able to make informed investment decisions about<span style=\"font-weight: bolder;\"> buying, holding, or selling a stock.</span></p><p dir=\"ltr\" style=\"color: rgb(33, 37, 41); font-family: \"Open Sans\", sans-serif; text-align: justify;\">So without any further ado, enroll in the course right now!</p>', 1, NULL, NULL, NULL, NULL, NULL, 0, '', '2024-01-04 21:42:51', '2024-02-01 02:12:09', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(10, 48, 52, 184, NULL, NULL, 0, 'Stock Market Investment: How to Earn by Investing', '', NULL, 3000.00, 10.00, 0, 'navieasoft limited', '04:12:32', 'beginner', '<p style=\"color: rgb(33, 37, 41); font-family: \"Open Sans\", sans-serif; text-align: justify;\">This course is perfect for you if you are someone who <span style=\"font-weight: bolder;\">wants to start investing in the stock market. </span>There are many misconceptions or myths surrounding stock market investment. In this course, such myths are debunked so that you can start your investment journey with the right information and correct mind setup. </p><p dir=\"ltr\" style=\"color: rgb(33, 37, 41); font-family: \"Open Sans\", sans-serif; text-align: justify;\">The course includes <span style=\"font-weight: bolder;\">understanding the stock market </span>and how it works, different types of stocks and stock market terminology, fundamental analysis techniques to evaluate stocks, risk management, the process of opening a brokerage account and making your first trade, and how to create your stock portfolio. </p><p dir=\"ltr\" style=\"color: rgb(33, 37, 41); font-family: \"Open Sans\", sans-serif; text-align: justify;\">By the end of the course, participants will have a solid understanding of the stock market and be able to make informed investment decisions about<span style=\"font-weight: bolder;\"> buying, holding, or selling a stock.</span></p><p dir=\"ltr\" style=\"color: rgb(33, 37, 41); font-family: \"Open Sans\", sans-serif; text-align: justify;\">So without any further ado, enroll in the course right now!</p>', 1, NULL, NULL, NULL, NULL, NULL, 0, '', '2024-01-04 21:42:51', '2024-01-05 08:05:29', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(11, 60, 0, 184, NULL, NULL, 0, 'Teaches Strategic Branding & Visioning', NULL, NULL, 1000.00, 10.00, 0, 'Navieasoft', '12', 'level', '<p><span style=\"font-family: &quot;Open Sans&quot;, Arial, sans-serif; text-align: justify;\">It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using \'Content here, content here\', making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for \'lorem ipsum\' will uncover many web sites still in their infancy. Various versions have evolved over the years, sometimes by accident, sometimes on purpose (injected humour and the like).</span><br></p>', 1, NULL, NULL, NULL, NULL, NULL, 1, 'https://www.youtube.com/watch?v=O4BwvpVJ17k', '2024-01-08 00:18:37', '2024-01-08 00:18:37', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(12, 61, 0, 177, NULL, NULL, 0, 'Teaches Strategic Financial Leadership', NULL, NULL, 5500.00, 10.00, 0, 'Navieasoft', '12', 'level', '<p><span style=\"font-family: \"Open Sans\", Arial, sans-serif; text-align: justify;\">Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old. Richard McClintock, a Latin professor at Hampden-Sydney College in Virginia, looked up one of the more obscure Latin words, consectetur, from a Lorem Ipsum passage, and going through the cites of the word in classical literature, discovered the undoubtable source. Lorem Ipsum comes from sections 1.10.32 and 1.10.33 of \"de Finibus Bonorum et Malorum\" (The Extremes of Good and Evil) by Cicero, written in 45 BC. This book is a treatise on the theory of ethics, very popular during the Renaissance. The first line of Lorem Ipsum, \"Lorem ipsum dolor sit amet..\", comes from a line in section 1.10.32.</span><br></p>', 1, NULL, NULL, NULL, NULL, NULL, 1, 'https://www.youtube.com/watch?v=O4BwvpVJ17k', '2024-01-08 00:21:01', '2024-01-08 00:22:34', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(13, NULL, 0, 265, NULL, NULL, 1, 'uhbyujh', NULL, NULL, 78.00, 78.00, 0, NULL, '11', 'Enim suscipit blandi', '', 1, NULL, NULL, NULL, NULL, NULL, 0, '', '2024-01-10 02:54:48', '2024-02-01 02:07:54', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(14, 48, 52, 265, NULL, NULL, 1, 'Master Course Of Java', NULL, NULL, 300.00, 10.00, 1, 'Porai.org', '200', 'High', '<p>this is description. thank you..</p>', 1, NULL, NULL, NULL, NULL, NULL, 0, '', '2024-01-10 04:01:45', '2024-02-01 02:05:09', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(15, 48, 52, 284, NULL, NULL, 1, 'Laravel for Beginners', 'Laravel Development', NULL, 150.00, 50.00, 1, 'Navieasoft', '01:00:00', 'Intermediate', '<p>Laravel values beauty. We love clean code just as much as you do. Simple, elegant syntax puts amazing functionality at your fingertips. Every feature has been thoughtfully considered to provide a wonderful developer experience.&nbsp;</p><p>Laravel values beauty. We love clean code just as much as you do. Simple, elegant syntax puts amazing functionality at your fingertips. Every feature has been thoughtfully considered to provide a wonderful developer experience.&nbsp;<span style=\"font-size: 0.875rem;\">Laravel values beauty. We love clean code just as much as you do. Simple, elegant syntax puts amazing functionality at your fingertips. Every feature has been thoughtfully considered to provide a wonderful developer experience.</span></p><p>Laravel values beauty. We love clean code just as much as you do. Simple, elegant syntax puts amazing functionality at your fingertips. Every feature has been thoughtfully considered to provide a wonderful developer experience.<span style=\"font-size: 0.875rem;\"><br></span><br></p>', 1, NULL, NULL, NULL, NULL, NULL, 0, '', '2024-02-15 10:22:32', '2024-02-15 10:30:40', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(17, 74, 75, 240, NULL, NULL, 1, 'PAPER I', NULL, NULL, 1000.00, 5.00, 0, NULL, NULL, 'BEGINNER', '<p>BLAH BLAH COURSE ABOUT..</p>', 1, NULL, NULL, NULL, NULL, NULL, 0, '', '2024-02-26 15:43:20', '2024-02-26 15:57:14', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(18, 74, 75, 240, NULL, NULL, NULL, 'PAPER II', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '', '', 1, NULL, NULL, NULL, NULL, NULL, 0, '', '2024-02-26 16:00:48', '2024-02-26 16:00:48', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(19, 74, 76, 240, NULL, NULL, NULL, 'KNOWLEDGE', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '', '', 1, NULL, NULL, NULL, NULL, NULL, 0, '', '2024-02-26 16:03:43', '2024-02-26 16:03:43', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(20, 77, 0, 240, NULL, NULL, NULL, 'MRCP PART I', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '', '', 1, NULL, NULL, NULL, NULL, NULL, 0, '', '2024-02-26 16:07:23', '2024-02-26 16:07:23', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(22, 48, 51, NULL, 1, NULL, 1, 'Computer science and engineering', NULL, NULL, NULL, 10.00, 0, 'Navieasoft', NULL, NULL, '<p>vds&nbsp; fvsdrf dsf&nbsp;</p>', 1, NULL, NULL, NULL, NULL, NULL, 0, 'https://www.youtube.com/watch?v=O4BwvpVJ17k', '2024-03-09 03:15:03', '2024-03-09 03:15:03', 'university', 0, 0, 2, 5, 15, 2, 10000, 1000, 10000, 4, '2024-03-07', '2024-03-30', '', '', '<p>ds fcdsf s&nbsp;</p>', '100');

--
-- Indexes for dumped tables
--

--
-- Indexes for table `courses`
--
ALTER TABLE `courses`
  ADD PRIMARY KEY (`id`);

--
-- AUTO_INCREMENT for dumped tables
--

--
-- AUTO_INCREMENT for table `courses`
--
ALTER TABLE `courses`
  MODIFY `id` bigint(20) UNSIGNED NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=23;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
